SRC_URI += "file://ikconfig.cfg \
            file://systemtap.cfg \
            file://oprofile.cfg \
            file://lttng.cfg \
            file://kgdb.cfg \
            file://dynamic-probe-insertion-kprobe.cfg \
            file://kexec.cfg \
            file://coredump.cfg \
            file://bootchart.cfg \
            file://latencytop.cfg \
            file://posix-mqueue.cfg \
            file://ramdisk.cfg \
            file://pseudo-tty.cfg \            
            file://ftrace.cfg \
            file://lock-debug.cfg \            
            file://dyndebug.cfg \
            file://kprobes.cfg \
            file://cma.cfg \
            file://crash.cfg \
           "
