#!/bin/sh
### BEGIN INIT INFO
# Provides:          force-usb-power
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Zynq zedboard turn on USB OTG to host mode (enabling +5V power rail)
### END INIT INFO

. /etc/init.d/functions

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

RETVAL=0

case "$1" in
    start)
	echo -n "Forcing USB OTG to host mode (enabling +5V power rail): "
	devmem2 0xe0002170 w 0x600a0067
        ;;

    stop)
	echo -m "Forcing USB OTG to device mode (disabling +5V power rail): "
	devmem2 0xe0002170 w 0x600a0007
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    *)
        echo "usage: $0 { start | stop | restart }"
        ;;
esac

exit $RETVAL

